=== shirogin/whats-your-choice-server/cards/schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"id": {
			"type": "string"
		},
		"name": {
			"type": "string"
		},
		"image": {
			"type": "string",
			"format": "uri"
		},
		"cards": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"id": {
						"type": "number"
					},
					"name": {
						"type": "string"
					},
					"image": {
						"type": "string",
						"format": "uri"
					}
				},
				"required": ["id", "name", "image"]
			}
		}
	},
	"required": ["id", "name", "cards", "image"]
}

=== shirogin/whats-your-choice-server/cards/berserk.json
{
  "id": "berserk",
  "name": "Berserk",
  "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/gambinojpg.png",
  "cards": [
    {
      "id": 0,
      "name": "Adon",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/adonpng.png"
    },
    {
      "id": 1,
      "name": "Azanne",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/azannejpg.png"
    },
    {
      "id": 2,
      "name": "Bakiraka1",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/bakiraka1jpg.png"
    },
    {
      "id": 3,
      "name": "Bakiraka2",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/bakiraka2jpg.png"
    },
    {
      "id": 4,
      "name": "Bakiraka2silat",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/bakiraka2silatjpg.png"
    },
    {
      "id": 5,
      "name": "Betty",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/bettyjpg.png"
    },
    {
      "id": 6,
      "name": "Bonebeard2",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/bonebeard2jpg.png"
    },
    {
      "id": 7,
      "name": "Boscogn",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/boscognjpg.png"
    },
    {
      "id": 8,
      "name": "Bouc",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/boucpng.png"
    },
    {
      "id": 9,
      "name": "Captain",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/captainpng.png"
    },
    {
      "id": 10,
      "name": "Carkus",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/carkuspng.png"
    },
    {
      "id": 11,
      "name": "Casca1",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/casca1jpg.png"
    },
    {
      "id": 12,
      "name": "Casca2",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/casca2jpg.png"
    },
    {
      "id": 13,
      "name": "Chitch",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/chitchjpg.png"
    },
    {
      "id": 14,
      "name": "Daiba",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/daibajpg.png"
    },
    {
      "id": 15,
      "name": "Danann",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/danannpng.png"
    },
    {
      "id": 16,
      "name": "Dis1",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/dis1jpg.png"
    },
    {
      "id": 17,
      "name": "Dis2",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/dis2jpg.png"
    },
    {
      "id": 18,
      "name": "Dis3",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/dis3jpg.png"
    },
    {
      "id": 19,
      "name": "Dis4",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/dis4jpg.png"
    },
    {
      "id": 20,
      "name": "Dis5",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/dis5jpg.png"
    },
    {
      "id": 21,
      "name": "Donjpeg",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/donjpeg.png"
    },
    {
      "id": 22,
      "name": "Eggapostle",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/eggapostlejpg.png"
    },
    {
      "id": 23,
      "name": "Enochpriest",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/enochpriestpng.png"
    },
    {
      "id": 24,
      "name": "Erica",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/ericajpg.png"
    },
    {
      "id": 25,
      "name": "Evarella",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/evarellajpg.png"
    },
    {
      "id": 26,
      "name": "Farnese2",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/farnese2jpg.png"
    },
    {
      "id": 27,
      "name": "Flora1",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/flora1jpg.png"
    },
    {
      "id": 28,
      "name": "Fossjpeg",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/fossjpeg.png"
    },
    {
      "id": 29,
      "name": "Gaiseric",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/gaisericjpg.png"
    },
    {
      "id": 30,
      "name": "Gambino",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/gambinojpg.png"
    },
    {
      "id": 31,
      "name": "Ganishka",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/ganishkajpg.png"
    },
    {
      "id": 32,
      "name": "Gaston",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/gastonjpg.png"
    },
    {
      "id": 33,
      "name": "Gedfring",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/gedfringpng.png"
    },
    {
      "id": 34,
      "name": "Gennon",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/gennonjpg.png"
    },
    {
      "id": 35,
      "name": "Gh1",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/gh1jpg.png"
    },
    {
      "id": 36,
      "name": "Gh2",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/gh2jpg.png"
    },
    {
      "id": 37,
      "name": "Gh3",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/gh3jpg.png"
    },
    {
      "id": 38,
      "name": "Gh4",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/gh4jpg.png"
    },
    {
      "id": 39,
      "name": "Gh5",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/gh5jpg.png"
    },
    {
      "id": 40,
      "name": "Godo",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/godojpg.png"
    },
    {
      "id": 41,
      "name": "Griffith1",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/griffith1jpg.png"
    },
    {
      "id": 42,
      "name": "Griffith2",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/griffith2png.png"
    },
    {
      "id": 43,
      "name": "Griffith3",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/griffith3png.png"
    },
    {
      "id": 44,
      "name": "Grunbeld",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/grunbeldjpg.png"
    },
    {
      "id": 45,
      "name": "Guts2",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/guts2png.png"
    },
    {
      "id": 46,
      "name": "Guts3",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/guts3jpg.png"
    },
    {
      "id": 47,
      "name": "Guts4 020149",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/guts4-020149jpg.png"
    },
    {
      "id": 48,
      "name": "Guts5",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/guts5png.png"
    },
    {
      "id": 49,
      "name": "Irvine",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/irvinejpg.png"
    },
    {
      "id": 50,
      "name": "Isidro",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/isidrojpg.png"
    },
    {
      "id": 51,
      "name": "Ismajpeg",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/ismajpeg.png"
    },
    {
      "id": 52,
      "name": "Jarif",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/jarifpng.png"
    },
    {
      "id": 53,
      "name": "Jerome",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/jeromejpg.png"
    },
    {
      "id": 54,
      "name": "Jilldad",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/jilldadpng.png"
    },
    {
      "id": 55,
      "name": "Jill",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/jillpng.png"
    },
    {
      "id": 56,
      "name": "Judo",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/judojpg.png"
    },
    {
      "id": 57,
      "name": "Julius",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/juliusjpg.png"
    },
    {
      "id": 58,
      "name": "King1",
      "image": "https://tiermaker.com/images/chart/chart/berserk-characters-main-and-minor-564305/king1png.png"
    },
    {
